<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Payroll;
use App\Models\Payslip;
use App\Models\PayslipItem;
use App\Models\User;
use App\Services\StatutoryService;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * Seeds six months of demonstration payroll history for a single employee.
 *
 * This writes SAMPLE figures, not real pay. Every payroll it creates is tagged
 * with self::DEMO_TAG in finance_note, which is both how the seeder stays
 * idempotent and how `payroll:demo-clear` finds rows to remove.
 *
 * Safety properties (deliberate — the older PayrollDemoSeeder has none of these):
 *  - never truncates any table;
 *  - refuses to touch a payroll it did not create, so a real payroll run for the
 *    same month is left completely alone;
 *  - re-runnable without duplicating rows;
 *  - fully reversible via `php artisan payroll:demo-clear`.
 *
 * Target employee defaults to DEMO_EMPLOYEE_ID and can be overridden:
 *   DEMO_PAYROLL_EMPLOYEE=EMP-0017 php artisan db:seed --class=DemoPayrollHistorySeeder
 */
class DemoPayrollHistorySeeder extends Seeder
{
    /** Marks a payroll as seeder-owned demo data. Do not change casually. */
    public const DEMO_TAG = 'DEMO DATA - generated by DemoPayrollHistorySeeder. Not a real payroll run.';

    /** Employee to seed when DEMO_PAYROLL_EMPLOYEE is not set. */
    private const DEMO_EMPLOYEE_ID = 'EMP-0017';

    private const MONTHS = 6;

    /**
     * Default monthly gross at the start of the window, before the mid-window raise.
     * Overridable with DEMO_PAYROLL_GROSS.
     *
     * The default sits above the new-regime 87A rebate threshold (₹12L taxable) on
     * purpose: below it TDS computes to a legitimate zero and the demo shows no tax
     * line. A lower override (e.g. ₹50,000) is fine — it simply won't show TDS.
     */
    private const OPENING_GROSS = 125000.0;

    /**
     * Default raise applied from the 4th month onward, so the trend chart shows a
     * step. Overridable with DEMO_PAYROLL_RAISE; set it to 1 for a flat window.
     */
    private const RAISE_MULTIPLIER = 1.08;

    public function run(): void
    {
        $employee = $this->resolveEmployee();

        if (! $employee) {
            $this->command?->error('Demo payroll: no matching employee found. Nothing seeded.');

            return;
        }

        $statutory = app(StatutoryService::class);
        $processorId = User::where('role', 'super_admin')->value('id') ?? $employee->user_id;

        $created = 0;
        $skipped = 0;

        // Oldest first so the raise lands in the right months.
        for ($i = self::MONTHS - 1; $i >= 0; $i--) {
            $period = Carbon::now()->startOfMonth()->subMonths($i);
            $monthIndex = self::MONTHS - 1 - $i;

            $payroll = $this->payrollFor($period, $processorId);

            if (! $payroll) {
                $skipped++;
                $this->command?->warn(
                    "Demo payroll: {$period->format('F Y')} already has a REAL payroll — left untouched."
                );

                continue;
            }

            $this->seedPayslip($employee, $payroll, $period, $monthIndex, $statutory);
            $created++;
        }

        $name = $employee->user?->name ?? "employee #{$employee->id}";
        $this->command?->info("Demo payroll: seeded {$created} month(s) for {$name} ({$employee->employee_id}).");

        if ($skipped > 0) {
            $this->command?->warn("Demo payroll: skipped {$skipped} month(s) that hold real payroll data.");
        }

        $this->command?->line('Remove it again with: php artisan payroll:demo-clear');
    }

    /** Resolve the target employee from env, then the default demo id, then give up. */
    private function resolveEmployee(): ?Employee
    {
        $wanted = env('DEMO_PAYROLL_EMPLOYEE', self::DEMO_EMPLOYEE_ID);

        return Employee::with('user')
            ->whereHas('user')
            ->where('employee_id', $wanted)
            ->first();
    }

    /**
     * Get (or create) the demo payroll for a period.
     *
     * Returns null when a payroll exists for that month that this seeder did not
     * create — real payroll is never modified.
     */
    private function payrollFor(Carbon $period, ?int $processorId): ?Payroll
    {
        $existing = Payroll::where('month', $period->format('F'))
            ->where('year', $period->year)
            ->first();

        if ($existing) {
            return $existing->finance_note === self::DEMO_TAG ? $existing : null;
        }

        // Salary credit lands on the last day of the month being paid.
        $creditedAt = $period->copy()->endOfMonth();

        return Payroll::create([
            'month' => $period->format('F'),
            'year' => $period->year,
            'cycle' => 'cycle_a',
            'status' => 'finalized',
            'processed_by' => $processorId,
            'processed_at' => $creditedAt->copy()->subDay(),
            'finance_approved_by' => $processorId,
            'finance_approved_at' => $creditedAt,
            'finance_note' => self::DEMO_TAG,
        ]);
    }

    /** Build one month's payslip and its earning/deduction lines. */
    private function seedPayslip(
        Employee $employee,
        Payroll $payroll,
        Carbon $period,
        int $monthIndex,
        StatutoryService $statutory,
    ): void {
        $gross = $this->grossFor($monthIndex);

        // Indian structure: Basic 40% of gross, HRA 50% of Basic (metro),
        // statutory-friendly fixed allowances, Special Allowance balances to gross.
        $basic = round($gross * 0.40, 2);
        $hra = round($basic * 0.50, 2);
        $conveyance = 1600.0;
        $medical = 1250.0;
        $special = round($gross - ($basic + $hra + $conveyance + $medical), 2);

        $earnings = [
            'Basic Pay' => $basic,
            'House Rent Allowance' => $hra,
            'Special Allowance' => $special,
            'Conveyance Allowance' => $conveyance,
            'Medical Allowance' => $medical,
        ];

        // Computed by the app's own statutory engine rather than invented figures.
        // PF caps the wage inside the service, so pass the full basic and let the
        // date-resolved ceiling apply.
        $pf = $statutory->providentFundEmployee($basic, $period);
        $pt = $statutory->professionalTax($gross, $period, 'MH');
        $tds = $statutory->monthlyTds($gross, $period);

        $deductions = array_filter([
            'Provident Fund (Employee)' => $pf,
            'Professional Tax' => $pt,
            'TDS' => $tds,
        ], fn ($amount) => $amount > 0);

        $totalDeductions = round(array_sum($deductions), 2);
        $net = round($gross - $totalDeductions, 2);

        $payslip = Payslip::updateOrCreate(
            ['payroll_id' => $payroll->id, 'employee_id' => $employee->id],
            [
                'gross_salary' => $gross,
                'total_deductions' => $totalDeductions,
                'net_salary' => $net,
                'status' => 'paid',
            ],
        );

        // Rebuild lines so a re-run cannot stack duplicates.
        PayslipItem::where('payslip_id', $payslip->id)->delete();

        foreach ($earnings as $name => $amount) {
            PayslipItem::create([
                'payslip_id' => $payslip->id,
                'name' => $name,
                'amount' => $amount,
                'type' => 'earning',
            ]);
        }

        foreach ($deductions as $name => $amount) {
            PayslipItem::create([
                'payslip_id' => $payslip->id,
                'name' => $name,
                'amount' => $amount,
                'type' => 'deduction',
            ]);
        }

        // Employer side — informational on the payslip, not deducted from net.
        // The service caps the wage internally against the date-resolved ceiling.
        foreach ([
            'Provident Fund (Employer)' => $statutory->providentFundEmployer($basic, $period),
            'Pension Scheme (Employer)' => $statutory->pensionSchemeEmployer($basic, $period),
        ] as $name => $amount) {
            if ($amount <= 0) {
                continue;
            }

            PayslipItem::create([
                'payslip_id' => $payslip->id,
                'name' => $name,
                'amount' => $amount,
                'type' => 'employer_contribution',
            ]);
        }

        $payroll->update([
            'total_payout' => round((float) $payroll->payslips()->sum('net_salary'), 2),
            'deductions' => round((float) $payroll->payslips()->sum('total_deductions'), 2),
        ]);
    }

    /** Monthly gross for a month index, applying the mid-window raise. */
    private function grossFor(int $monthIndex): float
    {
        $opening = (float) env('DEMO_PAYROLL_GROSS', self::OPENING_GROSS);
        $raise = (float) env('DEMO_PAYROLL_RAISE', self::RAISE_MULTIPLIER);

        $gross = $monthIndex >= 3 ? $opening * $raise : $opening;

        return round($gross, 2);
    }
}
