<?php

namespace Database\Seeders;

use App\Models\LeaveType;
use Illuminate\Database\Seeder;

class LeaveTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'name' => 'Casual Leave',
                'code' => 'CL',
                'category' => 'annual',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#3B82F6',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => true,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => 12,
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Sick Leave',
                'code' => 'SL',
                'category' => 'sick',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#F59E0B',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => true,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => true,
                'annual_allocation_days' => 6,
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Earned Leave',
                'code' => 'EL',
                'category' => 'annual',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#1DB77A',
                'allow_carry_forward' => true,
                'carry_forward_limit' => 30,
                'allow_encashment' => true,
                'is_sandwich_applicable' => true,
                'allow_half_day' => true,
                'is_monthly_accrual' => true,
                'accrual_days_per_month' => 1.75,
                'gender_restriction' => 'none',
                'probation_restricted' => true,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => null, // Accrual-based — no upfront allocation
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Maternity Leave',
                'code' => 'ML',
                'category' => 'mdl',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => false,
                'hr_remark_required' => true,
                'color' => '#EC4899',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => false,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'female',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => true,
                'annual_allocation_days' => 180,
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Paternity Leave',
                'code' => 'PL',
                'category' => 'paternity',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => false,
                'hr_remark_required' => true,
                'color' => '#6366F1',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => false,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'male',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => 15,
                'attachment_required' => false,
                'annual_allocation_days' => 15,
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Bereavement Leave',
                'code' => 'BL',
                'category' => 'bereavement',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#64748B',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => false,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => 5,
                'attachment_required' => true,
                'annual_allocation_days' => 5,
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Comp Off',
                'code' => 'CO',
                'category' => 'comp_off',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#06B6D4',
                'allow_carry_forward' => true,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => true,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => null, // Earned via overtime — manual credit only
                'is_system_controlled' => false,
            ],
            [
                'name' => 'Leave Without Pay',
                'code' => 'LWP',
                'category' => 'lwp',
                'is_paid' => false,
                'allow_paid_request' => false,
                'allow_unpaid_request' => true,
                'allow_hr_override' => false,
                'hr_remark_required' => false,
                'color' => '#EF4444',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => true,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => null, // Unlimited — system generated
                'is_system_controlled' => true,
            ],
            [
                'name' => 'Unauthorized Leave',
                'code' => 'UL',
                'category' => 'unauthorized',
                'is_paid' => false,
                'allow_paid_request' => false,
                'allow_unpaid_request' => false,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#DC2626',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => true,
                'allow_half_day' => false,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => null, // Generated from attendance violations
                'is_system_controlled' => true,
            ],
            [
                'name' => 'Work From Home',
                'code' => 'WFH',
                'category' => 'wfh',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => false,
                'allow_hr_override' => false,
                'hr_remark_required' => false,
                'color' => '#8B5CF6',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => false,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => null, // Request-based — no fixed quota
                'is_system_controlled' => true,
            ],
            [
                'name' => 'Custom Leave',
                'code' => 'CUS',
                'category' => 'custom',
                'is_paid' => true,
                'allow_paid_request' => true,
                'allow_unpaid_request' => true,
                'allow_hr_override' => true,
                'hr_remark_required' => true,
                'color' => '#10B981',
                'allow_carry_forward' => false,
                'carry_forward_limit' => 0,
                'allow_encashment' => false,
                'is_sandwich_applicable' => false,
                'allow_half_day' => true,
                'is_monthly_accrual' => false,
                'accrual_days_per_month' => 0,
                'gender_restriction' => 'none',
                'probation_restricted' => false,
                'notice_period_restricted' => false,
                'max_consecutive_days' => null,
                'attachment_required' => false,
                'annual_allocation_days' => null, // Configurable per company policy
                'is_system_controlled' => false,
            ],
        ];

        foreach ($types as $data) {
            LeaveType::updateOrCreate(['code' => $data['code']], $data);
        }
    }
}
